# Generated by Django 3.2.7 on 2022-03-25 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sliders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='image',
            field=models.ImageField(upload_to='sliders/media', verbose_name='تصویر'),
        ),
    ]
