# Generated by Django 4.0.3 on 2022-03-11 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='توضیحات محصول')),
                ('price', models.IntegerField(blank=True, default='1000', null=True, verbose_name='قیمت')),
                ('product_size', models.CharField(max_length=500, verbose_name='سایز محصول')),
                ('color', models.CharField(blank=True, max_length=200, null=True, verbose_name='رنگ')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products', verbose_name='تصویر محصول')),
                ('brand', models.CharField(max_length=200, verbose_name='برند')),
                ('new_type', models.CharField(choices=[('جدید', 'بله'), (' ', 'خیر')], default='no', max_length=200, verbose_name='جدید')),
                ('special', models.BooleanField(default=False, verbose_name='محصول ویژه')),
                ('active', models.BooleanField(default=False, verbose_name='موجود / ناموجود')),
                ('view', models.IntegerField(default=0, verbose_name='تعداد بازدید')),
                ('categories', models.ManyToManyField(to='category.category', verbose_name='دسته بندی ها')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
            },
        ),
    ]
