# Generated by Django 4.0.3 on 2022-03-14 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان سایت')),
                ('address', models.CharField(blank=True, max_length=500, null=True, verbose_name='آدرس')),
                ('phone', models.CharField(blank=True, max_length=25, null=True, verbose_name='شماره تماس')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logo', verbose_name='لوگوی سایت(48*48)')),
                ('description', models.TextField(verbose_name='توضیحات درباره سایت')),
            ],
            options={
                'verbose_name': 'تنظیم سایت',
                'verbose_name_plural': 'تنظیم اطلاعات سایت',
            },
        ),
    ]
