# Generated by Django 3.2.7 on 2022-03-28 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_product_categories'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderDetail',
            new_name='Order',
        ),
    ]
