# Generated by Django 3.2.7 on 2022-03-28 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_rename_orderdetail_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order',
            new_name='card',
        ),
    ]
